version: '3'
services:
  db:
    image: mysql:latest
    environment: 
      MYSQL_DATABASE: lamp_stack
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
  www:
    image: php:apache-bullseye
    volumes:
      - "./:/var/www/html"
    ports: 
      - 80:80
      - 443:443