version: '3'
services:
  db:
    image: mysql:latest
    environment: 
      MYSQL_DATABASE: lamp_stack
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-network
  www:
    depends_on:
      - db
    image: php:latest
    volumes:
      - "./:/var/www/html"
    ports: 
      - 80:80
      - 443:443
    networks:
      - lamp-network
    commands:
      bash -c "
        docker-php-ext-install mysqli &&
        docker-php-ext-enable mysqli &&
        apache2-foreground"
  phpmyadmin:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-network
networks:
  lamp-network:
    driver: bridge
