
version: '3'
services:
  db:
    image: mysql:latest
    environment: 
      MYSQL_DATABASE: lamp_stack
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-network
  www:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    image: php:apache-bullseye
    volumes:
      - "./:/var/www/html"
    ports: 
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - lamp-network
  phpmyadmin:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-network
networks:
  lamp-network:
    driver: bridge
