version: '3'
services:
  db:
    image: mysql:latest
    environment: 
      MYSQL_DATABASE: lamp_stack
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  www:
    image: php:8.1-apache-buster
    volumes:
      - "./:/var/www/html"
    ports: 
      - 80:80
      - 443:443
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
